"""Golden-image regression test for the detection + OCR pipeline.

This single test is the tripwire for the whole vision stack. It catches, in one
assertion:

  * model-load breakage -- e.g. ultralytics < 8.3.94 cannot unpickle the
    YOLO11 modules (C3k2, C2PSA) in Models/BOX_TRAINED.pt and dies with
    "AttributeError: Can't get attribute 'C3k2'". That is exactly the state
    requirements.txt shipped in before this branch.
  * ultralytics API drift in the detection call
  * EasyOCR output changes
  * CS2 UI changes that move the item-name text out of the sampled region

It is marked `slow` because the first run downloads EasyOCR's detection and
recognition weights (~100 MB). Run just the fast tests with:

    pytest -m "not slow"

FIXTURE NOTE
------------
The fixture is `Training_Images/image.png`, a 2560x1440 English screenshot.

`Training_Images/TEST FINAL.png` looks like the obvious candidate but is a
*German* client screenshot -- it OCRs to 'Mauf Kostenlos',
'Versiegeltes ... Graffito' and so on, and would need German EasyOCR weights.

The committed `output/text_*.txt` files were generated by an older revision of
the cropping code and contain extra trailing UI text ("Free", "Requires ... key",
the graffiti colour in brackets). The current pipeline returns a cleaner prefix.
The expectations below are what the pipeline actually produces today, verified
by running it; they are deliberately substring assertions so a harmless OCR
tweak does not fail the build while a real regression still does.
"""

import os

import pytest

pytestmark = pytest.mark.slow

FIXTURE = os.path.join('Training_Images', 'image.png')

# Each entry: substrings that must all appear in that slot's OCR text.
EXPECTED_SLOTS = [
    ['Revolution Case'],
    ['Sawed-Off', 'Forest DDPAT'],
    ['Sealed Graffiti', 'Sorry'],
    ['Sealed Graffiti'],
]


@pytest.fixture(scope='module')
def detected_texts(repo_root):
    from Src.ImageDetector.modified_detect_text import WeeklyDropProcessor

    image_path = os.path.join(repo_root, FIXTURE)
    assert os.path.exists(image_path), (
        f"Golden fixture missing: {image_path}. It must stay committed -- "
        f"this test is the only regression guard on the vision pipeline."
    )

    model_path = os.path.join(repo_root, 'Models', 'BOX_TRAINED.pt')
    processor = WeeklyDropProcessor(model_path)
    return processor.process_image(image_path, save_crops=False)


def test_model_loads_and_exposes_the_box_class():
    """Fastest possible check that the weights still deserialize.

    If this fails with AttributeError mentioning C3k2 or C2PSA, ultralytics has
    been downgraded below 8.3.94.
    """
    from ultralytics import YOLO

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    model = YOLO(os.path.join(repo_root, 'Models', 'BOX_TRAINED.pt'))

    assert 'Box' in model.names.values()


def test_detects_exactly_four_slots(detected_texts):
    """A CS2 care package always offers four choices."""
    assert len(detected_texts) == 4


@pytest.mark.parametrize('index,fragments', list(enumerate(EXPECTED_SLOTS)))
def test_slot_text_still_recognised(detected_texts, index, fragments):
    actual = detected_texts[index]
    for fragment in fragments:
        assert fragment.lower() in actual.lower(), (
            f"Slot {index} lost the expected text {fragment!r}. Got {actual!r}. "
            f"Either OCR regressed or the CS2 drop UI changed."
        )


def test_undetectable_image_raises_rather_than_guessing(repo_root, tmp_path):
    """A screenshot with no drop panel must fail loudly.

    The old code silently fell back to slicing the entire image into quarters,
    which produced four confident but completely wrong item names.
    """
    import numpy as np
    import cv2

    from Src.ImageDetector.modified_detect_text import (
        WeeklyDropProcessor, DetectionError,
    )

    blank = np.zeros((720, 1280, 3), dtype=np.uint8)
    blank_path = str(tmp_path / 'blank.png')
    cv2.imwrite(blank_path, blank)

    processor = WeeklyDropProcessor(os.path.join(repo_root, 'Models', 'BOX_TRAINED.pt'))

    with pytest.raises(DetectionError):
        processor.process_image(blank_path, save_crops=False)
